site_name: Pantsbuild
site_url: https://pantsbuild.org/docs/
docs_dir: markdown
use_directory_urls: true

# Theme
theme:
  name: material
  palette:
    primary: blue
  font:
    text: system-ui
    code: Roboto Mono
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.indexes
markdown_extensions:
  - admonition:
  - md_in_html:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - awesome-pages:
      filename: .nav.yaml
      collapse_single_pages: true
  - redirects:
      redirect_maps:
        "index.md": "introduction/welcome-to-pants.md"
  - search

extra_css:
  - css/extra.css

# GitHub
repo_name: pantsbuild/pants
repo_url: https://github.com/pantsbuild/pants
edit_uri: edit/main/docs/markdown
