site_name: Pantsbuild
site_url: https://pantsbuild.org/docs/
docs_dir: markdown
use_directory_urls: true

# Theme
theme:
  name: material
  palette:
    primary: blue
  font:
    text: system-ui
    code: Roboto Mono
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.indexes
markdown_extensions:
  - admonition:
  - md_in_html:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - redirects:
      redirect_maps:
        "index.md": "introduction/welcome-to-pants.md"

extra_css:
  - css/extra.css

# GitHub
repo_name: pantsbuild/pants
repo_url: https://github.com/pantsbuild/pants
edit_uri: edit/main/docs/markdown
# @TODO: Autogen this?

# nav:
#   - Introduction:
#       - introduction/how-does-pants-work.md
#       - introduction/language-support.md
#       - introduction/media.md
#       - introduction/news-room.md
#       - introduction/sponsorship.md
#       - introduction/testimonials.md
#       - introduction/welcome-to-pants.md
#       - introduction/who-uses-pants.md
#   - Getting Started:
#       - getting-started/index.md
#       - getting-started/prerequisites.md
#       - getting-started/installation.md
#       - getting-started/initial-configuration.md
#       - getting-started/example-repos.md
#       - getting-started/existing-repositories.md
#       - getting-started/manual-installation.md
#   - Getting Help:
#       - getting-help/getting-help.md
#       - The Pants community:
#           - getting-help/the-pants-community/index.md
#           - getting-help/the-pants-community/code-of-conduct.md
#           - getting-help/the-pants-community/team.md
#           - getting-help/the-pants-community/maintainers.md
#           - getting-help/the-pants-community/contentious-decisions.md
#       - getting-help/service-providers.md
