name: Auto Cherry-Picker

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      PR_number:
        description: The PR number to cherry-pick
        type: string
        required: true

jobs:
  picker:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cherry-Pick
        run: |
          build-support/bin/cherry_pick.sh ${{ github.event.pull_request.number || inputs.PR_number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
